#!/bin/bash

# update script for clamav db
# 

# if freshclam is not installed -> do nothing
if [ ! -x /usr/bin/freshclam ]; then
 exit 0
fi

DB_DIR=`grep DatabaseDirectory /etc/clamd.conf | awk '\{print $2\}'`
TOTAL_MEM=$(cat /proc/meminfo | grep ^MemTotal: | awk '\{print $2\}')

if [ $TOTAL_MEM -gt 2000000 ]; then
	LOG_FILE="/var/log/clamav/freshclam.log"
	if [ ! -f "$LOG_FILE" ]; then
	    touch "$LOG_FILE"
	    chmod 644 "$LOG_FILE"
	    chown clam.clam "$LOG_FILE"
	fi
	/usr/bin/freshclam \
	    --quiet \
	    --datadir="$DB_DIR" \
	    --log="$LOG_FILE"
else
	rm -f "$DB_DIR"/\{main.c?d,daily.c?d\}
fi
