#!/usr/bin/python

import os
import time
import sys
import syslog


def lamp_on(leds):
    i = 0
    for led in leds:
       f = open("/sys/class/leds/apu:%s/brightness" % led, "w")
       f.write("1")
       f.close()
    time.sleep(0.5)

def lamp_off(leds):
    i = 0
    for led in leds:
       f = open("/sys/class/leds/apu:%s/brightness" % led, "w")
       f.write("0")
       f.close()
    time.sleep(0.5)

def lamp_reset():
    f = open("/sys/class/leds/apu:1/brightness", "w")
    f.write("1")
    f.close()
    for led in range(2,3):
       f = open("/sys/class/leds/apu:%s/brightness" % led, "w")
       f.write("0")
       f.close()

if __name__ == "__main__":
    RESET = 50
    try:
        device = '/dev/apu_button_s1'
        tick = 0
        syslog.openlog('apu-button')
        if not os.path.exists(device):
            raise SystemExit
            sys.exit(1)
        while True:
            f = open(device, "r");
            v = f.read(1)
            f.close()
            if (v == "1"):
               tick = tick +1
               if (tick >= RESET):
                   syslog.syslog("Factory reset")
                   lamp_on([1,2])
                   lamp_reset()
                   os.system("/sbin/factory-default")
                   sys.exit(0)
            else:
               if (tick > 1):
                   syslog.syslog("Shutdown")
                   lamp_off([1])
                   lamp_reset()
                   os.system("/sbin/shutdown -h now")
               tick = 0
            time.sleep(0.2)
    except SystemExit:
        sys.stdout.write("No such file or directory: %s\n" % device)


