#!/bin/bash

modprobe leds-apu2 2>/dev/null
modprobe ledtrig-heartbeat 2>/dev/null
modprobe ledtrig_default_on 2>/dev/null

if [ -d /sys/class/leds/apu2:1/ ]; then
    for i in 1 2 3; do
        echo none > /sys/class/leds/apu2:$i/trigger
    done
    echo default-on > /sys/class/leds/apu2\:1/trigger
fi
