#!/bin/bash
#
# Wait until udev has done it's job, then start the real system-init procedure.
# Udev must not be able to create records inside the networks db before the system-init has run.
#

config=$(/usr/libexec/nethserver/nic-info)
hit=0

while true
do
    sleep 2
    last_config=$(/usr/libexec/nethserver/nic-info)
    if [ -n "$last_config" ] && [ "$config" == "$last_config" ] ; then
        hit=$((hit+1))
        if [ $hit -gt 2 ]; then
            break
        fi
    else
        config=$last_config
    fi
done

echo "[NOTICE] Ready to start system-init"
