#!/bin/bash
#
# Wait until udev has done it's job, then start the real system-init procedure.
# Udev must not be able to create records inside the networks db before the system-init has run.
#

config=$(/usr/libexec/nethserver/nic-info)

while true
do
    sleep 5
    last_config=$(/usr/libexec/nethserver/nic-info)
    if [ -n "$last_config" ] && [ "$config" == "$last_config" ] ; then
        break
    else
        config=$last_config
    fi
done

echo "[NOTICE] Ready to start system-init"
