#!/bin/bash

MODEL=`dmidecode -qs system-product-name`
MODEL=`echo "$MODEL" | /bin/tr '[:upper:]' '[:lower:]'`
if [ "$MODEL" != "apu2" ]; then
  exit 0
fi

modprobe leds-apu2
modprobe ledtrig-heartbeat
modprobe ledtrig_default_on

for i in 1 2 3
do
  echo heartbeat > /sys/class/leds/apu2:$i/trigger
done
